[package]
name = "meteo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build]
rustflags = ["-C", "link-arg=-pthread"]

[dependencies]
open-meteo-api = "0.1.3"
tokio = { version = "1", features = ["full"] }
reqwest = "0.12.4"
serde_json = "1.0.70"
